#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_secrets.py - 从 config.local.json 生成 firmware/esp32/src/secrets.local.h

用途:
    Wi-Fi / 网络配置统一真相源位于项目根 config.local.json。
    本脚本在编译固件前执行，把 JSON 转成 C 头文件供 #include 使用。
    同时被 pc/config.py 读取，实现 PC 端与固件共享同一份配置。

输入:
    - 项目根 config.local.json（用户手动创建，从 config.local.json.example 复制）
    - JSON 字段: wifi_ssid / wifi_pass / pc_host / pc_port / esp32_hostname

输出:
    - firmware/esp32/src/secrets.local.h（生成后不入库）
    - stdout 打印生成摘要；缺失字段按默认值填充并打 warning

退出码:
    0 - 成功（包括 config.local.json 不存在时，走回退模板）
    1 - 参数错误或严重错误

依赖:
    - Python 3.9+（仅使用标准库 json / pathlib / datetime）
    - aidlux 兼容：不使用第三方库、不使用 asyncio

用法:
    python scripts/gen_secrets.py
    # 或者 PlatformIO pre-build 自动调用
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Tuple

# --------------------------------------------------------------------------
# 路径
# --------------------------------------------------------------------------

PROJECT_DIR = Path(__file__).resolve().parent.parent
CONFIG_JSON = PROJECT_DIR / "config.local.json"
CONFIG_EXAMPLE = PROJECT_DIR / "config.local.json.example"
OUTPUT_HEADER = PROJECT_DIR / "firmware" / "esp32" / "src" / "secrets.local.h"

# --------------------------------------------------------------------------
# 默认值（与 firmware/esp32/src/secrets.h 保持一致）
# --------------------------------------------------------------------------

DEFAULTS: Dict[str, Any] = {
    "wifi_ssid": "your_wifi_ssid",
    "wifi_pass": "your_wifi_password",
    "pc_host": "192.168.1.20",
    "pc_port": 8888,
    "esp32_hostname": "esp32-voice",
}

# 宏名 -> JSON 字段（保持单一真相源：这里和 secrets.h / pc/config.py 保持同步）
FIELD_TO_MACRO: Dict[str, str] = {
    "wifi_ssid": "WIFI_SSID",
    "wifi_pass": "WIFI_PASS",
    "pc_host": "PC_HOST",
    "pc_port": "PC_PORT",
    "esp32_hostname": "ESP32_HOSTNAME",
}


def _c_escape(value: str) -> str:
    """把 Python 字符串转成 C 双引号字符串字面量内容（不含外层引号）。"""
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def _render_macro(name: str, value: Any) -> str:
    """根据字段值类型渲染 #define 行。"""
    if isinstance(value, int):
        return f"#define {name} {value}"
    if isinstance(value, str):
        return f'#define {name} "{_c_escape(value)}"'
    raise TypeError(f"unsupported value type for {name}: {type(value).__name__}")


def _load_config() -> Tuple[Dict[str, Any], bool]:
    """读取 config.local.json。

    返回 (config_dict, used_defaults)：
        - used_defaults=True 表示 JSON 不存在，走默认值（不报错，方便首次编译）
    """
    if not CONFIG_JSON.exists():
        return dict(DEFAULTS), True

    with CONFIG_JSON.open("r", encoding="utf-8") as f:
        data = json.load(f)

    if not isinstance(data, dict):
        print(f"[gen_secrets] ERROR: {CONFIG_JSON} 根必须是 JSON object", file=sys.stderr)
        sys.exit(1)

    # 忽略以 _ 开头的字段（用作注释，如 "_comment"）
    data = {k: v for k, v in data.items() if not k.startswith("_")}

    # 缺失字段用默认值补齐
    for key in DEFAULTS:
        data.setdefault(key, DEFAULTS[key])

    return data, False


def _validate(config: Dict[str, Any]) -> None:
    """轻量校验，避免把明显错误的值写进固件。"""
    for key in ("wifi_ssid", "wifi_pass", "pc_host", "esp32_hostname"):
        if not isinstance(config.get(key), str) or not config[key]:
            print(f"[gen_secrets] WARN: {key} 为空或类型错误，将使用默认值 {DEFAULTS[key]!r}", file=sys.stderr)
            config[key] = DEFAULTS[key]

    port = config.get("pc_port")
    if not isinstance(port, int) or not (1 <= port <= 65535):
        print(f"[gen_secrets] WARN: pc_port={port!r} 非法，回退到 {DEFAULTS['pc_port']}", file=sys.stderr)
        config["pc_port"] = DEFAULTS["pc_port"]


def _render_header(config: Dict[str, Any], used_defaults: bool) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source = "config.local.json.example（默认值）" if used_defaults else "config.local.json"

    lines = [
        "// ============================================================",
        "// secrets.local.h - GENERATED by scripts/gen_secrets.py",
        "// ============================================================",
        f"// Generated at : {now}",
        f"// Source       : {CONFIG_JSON.relative_to(PROJECT_DIR) if not used_defaults else CONFIG_EXAMPLE.relative_to(PROJECT_DIR)}",
        "// Do not edit  : 手动改动会被下次 gen_secrets.py 覆盖",
        "//                请编辑项目根 config.local.json",
        "// ============================================================",
        "",
        "#ifndef SECRETS_LOCAL_H",
        "#define SECRETS_LOCAL_H",
        "",
    ]

    for json_key, macro_name in FIELD_TO_MACRO.items():
        lines.append(f"// {json_key}")
        lines.append(_render_macro(macro_name, config[json_key]))
        lines.append("")

    lines.append("#endif  // SECRETS_LOCAL_H")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    config, used_defaults = _load_config()
    _validate(config)

    header = _render_header(config, used_defaults)

    OUTPUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_HEADER.write_text(header, encoding="utf-8")

    print(f"[gen_secrets] source : {CONFIG_JSON if not used_defaults else CONFIG_EXAMPLE}")
    print(f"[gen_secrets] output : {OUTPUT_HEADER.relative_to(PROJECT_DIR)}")
    print(f"[gen_secrets] wifi_ssid      = {config['wifi_ssid']}")
    print(f"[gen_secrets] pc_host        = {config['pc_host']}:{config['pc_port']}")
    print(f"[gen_secrets] esp32_hostname = {config['esp32_hostname']}")
    if used_defaults:
        print(f"[gen_secrets] NOTE : 未找到 config.local.json，使用默认值", file=sys.stderr)
        print(f"[gen_secrets]        请执行: cp {CONFIG_EXAMPLE.name} {CONFIG_JSON.name}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
